export const ZOMBIE_THRESHOLDS = {
  LINK_DAYS: 30,
  LINK_UNTOUCHED_DAYS: 7,
  TODO_DAYS: 14,
  PIN_DAYS: 30,
  MIN_COUNT_FOR_NUDGE: 3,
  MIN_COUNT_FOR_CLEANUP: 5,
  CLEANUP_FETCH_LIMIT: 20,
} as const

export const SIMILARITY_THRESHOLDS = {
  RELATED: 0.6,
  RESURFACE: 0.4,
  SEARCH: 0.1,
} as const
